### ISSUE TITLE
Google Translate API

### ISSUE THREAD

**Issue by AlexKollar** [AlexKollar/Cryptex#41]

**Comment by marvhus** [comment]
I'll look into it when I get home.

**Comment by marvhus** [comment]
I've found some [documentation](https://github.com/ssut/py-googletrans/blob/master/docs/index.rst) on it, but it just gives an error.

```
Traceback (most recent call last):
  File "translate_test.py", line 5, in <module>
    translation = translator.translate('안녕하세요.')
  File "/home/martin/.local/lib/python3.8/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/home/martin/.local/lib/python3.8/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/home/martin/.local/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/home/martin/.local/lib/python3.8/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group
```

with the code

```
from googletrans import Translator
translator = Translator()
translation = translator.translate('안녕하세요.')
print(translation.text)
```

**Comment by marvhus** [comment]
I found a [issue](https://github.com/ssut/py-googletrans/issues/299)
and apparently the fix is:
```bash
pip install googletrans==3.1.0a0
```
I'm going to test it now

**Comment by marvhus** [comment]
That seams to have fixed it.

**Comment by marvhus** [comment]
It should now be working
