### ISSUE TITLE
Fix this circular input glitch

### ISSUE THREAD

**Issue by AlexKollar** [AlexKollar/Cryptex#7]
`Traceback (most recent call last):
  File "/home/alex/github/myGit/Cryptex/cryptex/cryptex.py", line 17, in <module>
    exec(open("base64.py").read())
  File "<string>", line 2, in <module>
  File "/home/alex/github/myGit/Cryptex/cryptex/base64.py", line 23, in <module>
    base64_bytes = base64.b64encode(text2b64_bytes)
AttributeError: partially initialized module 'base64' has no attribute 'b64encode' (most likely due to a circular import)
`

**Comment by AlexKollar** [comment]
solved with the overhaul
